services:
  product-service:
    image: svebrant-product:latest # image built from /docker/Dockerfile.product
    container_name: product-service
    restart: unless-stopped
    environment:
      mongodb.uri: "mongodb://mongodb-product:27017"
    ports:
        - "8050:8050"
    depends_on:
      - mongodb-product
    networks:
      - svebrant_network