services:
  product-service:
    image: svebrant-product:latest # image built from /docker/Dockerfile.product
    container_name: product-service
    restart: unless-stopped
    environment:
      auth.bearer.token: "secret-dev-token-please-change"
      mongodb.uri: "mongodb://mongodb-product:27017"
      http.discount-client.base-url: "http://discount-service:8060"
    ports:
        - "8050:8050"
    depends_on:
      - mongodb-product
    networks:
      - svebrant_network

  discount-service:
    image: svebrant-discount:latest # image built from /docker/Dockerfile.discount
    container_name: discount-service
    restart: unless-stopped
    environment:
      auth.bearer.token: "secret-dev-token-please-change"
      mongodb.uri: "mongodb://mongodb-discount:27027"
    ports:
      - "8060:8060"
    depends_on:
      - mongodb-discount
    networks:
      - svebrant_network