service:
  name: product-service

mongodb:
  uri: "mongodb://localhost:27017"

http:
  discount-client:
    base-url: "http://localhost:8060"

ingest:
  productsFilePath: "/data/products.ndjson"
  discountsFilePath: "/data/discounts.ndjson"

ktor:
  application:
    modules:
      - com.svebrant.ApplicationKt.module
  deployment:
    port: 8050