service:
  name: product-service

ingest:
  productsFilePath: "/data/products.ndjson"
  discountsFilePath: "/data/discounts.ndjson"

ktor:
  application:
    modules:
      - com.svebrant.ApplicationKt.module
  deployment:
    port: 8050