service:
  name: discount-service

mongodb:
  uri: "mongodb://localhost:27027"

auth:
  bearer:
    token: "secret-dev-token-please-change"

ktor:
  application:
    modules:
      - com.svebrant.ApplicationKt.module
  deployment:
    port: 8060